-- MySQL Script generated by MySQL Workbench
-- Mon May 26 20:32:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_projecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projecto` DEFAULT CHARACTER SET utf8 ;
USE `db_projecto` ;

-- -----------------------------------------------------
-- Table `db_projecto`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projecto`.`ROLES` (
  `rol_codigo` INT NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projecto`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projecto`.`USUARIOS` (
  `rol_codigo` INT NOT NULL,  
  `usuario_codigo` INT NOT NULL AUTO_INCREMENT,
  `usuario_nombres` VARCHAR(100) NOT NULL,
  `usuario_apellidos` VARCHAR(100) NOT NULL,
  `usuario_identificador` VARCHAR(20) NOT NULL,
  `usuario_email` VARCHAR(50) NOT NULL,
  `usuario_pass` VARCHAR(200) NOT NULL,
  `usuario_estado` TINYINT NOT NULL,
  PRIMARY KEY (`usuario_codigo`),
  INDEX `ind_usuario_rol` (`rol_codigo` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_codigo`)
    REFERENCES `db_projecto`.`ROLES` (`rol_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
